apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  rhtap/gitops: rag-l1742392731938
  janus-idp.io/tekton: rag-l1742392731938
  backstage.io/kubernetes-id: rag-l1742392731938
  backstage.io/kubernetes-namespace: rhdh-app
  app.kubernetes.io/part-of: rag-l1742392731938
resources:
  - application-dev.yaml
