apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: rag-l1742392731938-gitops
  description: This is GitOps manifest for rag-l1742392731938   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:
    # ArgoCD apps from this template used rhtap-gitops as the grouping
    argocd/app-selector: rhtap/gitops=rag-l1742392731938
    janus-idp.io/tekton: rag-l1742392731938 
    backstage.io/kubernetes-id: rag-l1742392731938 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:rag-l1742392731938  
