apiVersion: batch/v1
kind: Job
metadata:
  name: dsp-clone-job-rag-l1742392731938-gitops
spec:
  template:
    metadata:
      name: dsp-clone-job-rag-l1742392731938-gitops
    spec:
      serviceAccountName: rag-l1742392731938-dsp-job
      containers:
        - name: initialize-dsp
          image: quay.io/redhat-ai-dev/utils:latest
          command:
            - /bin/bash
            - -c
            - |
              NS=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
              oc wait -l statefulset=rag-l1742392731938-notebook --for=condition=ready pod --timeout=300s
              oc exec  StatefulSet/rag-l1742392731938-notebook -- git clone https://github.com/rhdh-pai-qe/rag-l1742392731938
      restartPolicy: Never
